version: "3"
services:
  postgres:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: my_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes: []
